name: Upload to ghci.io

on:
  push:
    tags:
      - '**'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: "Upload to ghcr.io"
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix with good defaults
      uses: input-output-hk/install-nix-action@v20
      with:
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          substituters = https://cache.iog.io/ https://cache.nixos.org/
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download images from cache
      run: |
        nix build --builders "" --max-jobs 0 .#dockerImage -o dockerImage
        nix build --builders "" --max-jobs 0 .#submitApiDockerImage -o submitApiDockerImage        
    - name: Log in to ghcr.io
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload to ghcr.io
      run: |
        docker load < dockerImage
        docker image tag inputoutput/cardano-node:$GITHUB_SHA ghcr.io/input-output-hk/cardano-node:$GITHUB_REF_NAME
        docker push ghcr.io/input-output-hk/cardano-node:$GITHUB_REF_NAME
        docker load < submitApiDockerImage
        docker image tag inputoutput/cardano-submit-api:$GITHUB_SHA ghcr.io/input-output-hk/cardano-submit-api:$GITHUB_REF_NAME
        docker push ghcr.io/input-output-hk/cardano-submit-api:$GITHUB_REF_NAME
